function [fitresult, gof] = createFitLinear(x, meanFluorescence)
%CREATEFIT1(X,MEANFLUORESCENCE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: meanFluorescence
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Feb-2022 16:50:34


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, meanFluorescence );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'meanFluorescence vs. x', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'x', 'Interpreter', 'none' );
% ylabel( 'meanFluorescence', 'Interpreter', 'none' );
% grid on


